@startuml
title IRA Actor Diagram

left to right direction

agent "Image Display" as PACS
agent "Report Creator" as Report
agent "Worklist Client" as Worklist
agent "Evidence Creator" as App
agent "Watcher" as Watcher
agent "Content Creator" as Content
agent "Hub" as Hub
PACS ----- Hub : "[[rad-146.html Subscribe to Reporting Session RAD-146]] →\n[[rad-147.html Connect to Notification Channel RAD-147]] →\n[[rad-152.html Unsubscribe Session RAD-152]] →\n[[rad-153.html Get Current Context RAD-153]] →\n[[rad-154.html Distribute Context Event RAD-154]] ←\n[[rad-155.html Generate SyncErrror Event RAD-155]] ←\n[[rad-156.html Notify Error RAD-156]] →\n[[rad-148.html Open Report Context RAD-148]] →\n[[rad-149.html Close Report Context RAD-149]] →"
Report ----- Hub : "[[rad-146.html Subscribe to Reporting Session RAD-146]] →\n[[rad-147.html Connect to Notification Channel RAD-147]] →\n[[rad-152.html Unsubscribe Session RAD-152]] →\n[[rad-153.html Get Current Context RAD-153]] →\n[[rad-154.html Distribute Context Event RAD-154]] ←\n[[rad-155.html Generate SyncErrror Event RAD-155]] ←\n[[rad-156.html Notify Error RAD-156]] →\n[[rad-148.html Open Report Context RAD-148]] →\n[[rad-149.html Close Report Context RAD-149]] →"
Worklist ----- Hub : "[[rad-146.html Subscribe to Reporting Session RAD-146]] →\n[[rad-147.html Connect to Notification Channel RAD-147]] →\n[[rad-152.html Unsubscribe Session RAD-152]] →\n[[rad-153.html Get Current Context RAD-153]] →\n[[rad-154.html Distribute Context Event RAD-154]] ←\n[[rad-155.html Generate SyncErrror Event RAD-155]] ←\n[[rad-156.html Notify Error RAD-156]] →\n[[rad-148.html Open Report Context RAD-148]] →\n[[rad-149.html Close Report Context RAD-149]] →"
App -u---- Hub : "[[rad-146.html Subscribe to Reporting Session RAD-146]] ←\n[[rad-147.html Connect to Notification Channel RAD-147]] ←\n[[rad-152.html Unsubscribe Session RAD-152]] ←\n[[rad-153.html Get Current Context RAD-153]] ←\n[[rad-154.html Distribute Context Event RAD-154]] →\n[[rad-155.html Generate SyncErrror Event RAD-155]] →\n[[rad-156.html Notify Error RAD-156]] ←"
Watcher -u---- Hub : "[[rad-146.html Subscribe to Reporting Session RAD-146]] ←\n[[rad-147.html Connect to Notification Channel RAD-147]] ←\n[[rad-152.html Unsubscribe Session RAD-152]] ←\n[[rad-153.html Get Current Context RAD-153]] ←\n[[rad-154.html Distribute Context Event RAD-154]] →\n[[rad-155.html Generate SyncErrror Event RAD-155]] →\n[[rad-156.html Notify Error RAD-156]] ←"
Content ----- Hub: "[[rad-150.html Update Report Content RAD-150]] →\n[[rad-151.html Select Report Content RAD-151]] →"
@enduml