= Open Questions

== Editorial

. Use Word or IG?
    * I don't have Office. The free OneDrive version of Word does not support line numbering. Google Doc does not have line numbering either. I can use LibreOffice Write, but the graphics positioning are messed up.
    * I can show split screen with live preview and my text which has line numbers
    * Latest FHIRcast also using IG and include event templates
    * FHIRcast payload are using FHIR resources. FHIRcast defined events currently do not have corresponding resource profiles, but rather text specification and handcrafted examples.

=> Use IG

=> Create instructions for reviewers

=> Create sandbox

. Should the FHIRcast specification be
    * Generic actors with generic transactions, then define content profiles for reporting events. With this a reporting related actor will be grouped with one or more generic actors, and required to support a set of events defined as content profiles, or
    * Specific actors with specific transactions
    * Note: FHIRcast can be later used to address the open CP for IID that requires support for context switching. FHIRcast as a general mechanism has other use in the future.

== Use Cases
. Currently identified the following flows:
    * Simple use case: PACS launches Dictation System in context. No content sharing
    * Switching context
    * Reporting with content sharing: One way communication from PACS to Reporting
    * Reporting with selection: Radiologist can select something in the PACS, then use a voice command on the dictation system to do something based on the selection just made
    * Sync errors
    * Multiple application multiple context: Complex use case

. Is the Application Invoker optional to subscribe to the same topic that it manages in order to receive events on the topic from the Sync Application?
    * This seems to be unnecessary since changing context is done by HTTPS, not WSS. The WSS is only required for subscribers to receive notifications.
    * However, in 2.6, after the change context request is accepted, the Hub should broadcast the event, including the requester. But this will only work if the requester also subscribes to the same topic, which is not specified.

. Is there a case that the selection is done from the reporting system and the PACS should response?

== Application launching

. Since SMART on FHIR is out of scope, we still need a generic 'Launch Application [RAD-X0]' which does not define the specific how the Application Invoker launches the Sync Application, but it requires that #hub.url# and #hub.topic# be communicated. FHIRcast has a page showing some examples.
    * Or should we just reference the page in FHIRcast, which also includes information if SMART on FHIR is used

    => Keep the Launch Application line in diagram, but no transaction. Put the hub.url and hub.topic requirements in teh actor description for the Application Invoker.
    
. Who can invite applications to the session?
    * Any participants? Or the only initial driving application?
        ** Does it mean the driving application must be aware of all possible dependent applications?
    * Can any app submit *-close event?
        ** Potentially the Specialty App unintentionally send the *-close event?
            *** There needs to be configuration / policy that govern who can send *-close events
            *** Implies that we need to know who sends each event
                **** there is a subscriber's name that is optional - make this mandatory

=> Design for PC is that any participants in a session can invite new participants to the session
=> i.e. not the original driving application is the only app invoker to the session
=> ... think about security consideration. Note that it is the same users driving all the participating applications, i.e. all apps are running in the context of the user

. Can any app submit *-close event?

== FHIRcast

. Question: How stable is FHIRcast? Given FHIRcast is under active development
    * Are there any foreseeable changes that could affect our normative text?
    * Are there any "improvements" in the works that we would want to take advantage of, or may want to wait for completion?
        ** For example, FHIRcast content sharing would likely be particularly relevant to our reporting use case. So it would be good to be stable for us to build on it.    

. In multi-app scenarios, each app is launched independently.
    * Should a single common context event used for all app with the same #hub.topic#
    * Can different context event used (since different application may be configured to only accept certain context events) but using the same #hub.topic#

. Does switching context (e.g. from report 1 to report 2 when switching studies) requires a close of the first context before opening another one?
    * It is allowed to have *-open followed by another *-open to start a new context. Double check if there is an 'implicit close' semantics if *-open followed by another *-open. This means only the last context has to be explicitly closed.
    * What if the Radiologist has moved on to the next study before it received the *-close event from the reporting system for the previous study?
        ** Is it allowed to have *-close event not matching the most recent *-open event?

. FHIRcast started to model diagnostic reporting events with DiagnosticReport-* events. In the examples, it includes accession number as an identifier inside an ImagingStudy resource. In IMR, accession number is defined as an identifier in a ServiceRequest resource.

=> Question to the FHIRcast WG. Should it align with IMR?

. How to support multiple instances of the same resource type?
    * Current study vs prior study (i.e. prior study context does not override current study context)
    * Switching different prior studies
    * Okay for multi-tab to single-tab application synchronization since there is always a single context in the sync app. What if multi-tab to multi-tab sync?
        * How to communicate the second context is supposed to be open in parallel of the first context? or as a replacemenet?

. FHIRcast requires the hub to automatically send the last *-open context event to all new subscribers.
    * Alternatively, my preference is that we can require the subscribers to always send a Get Context Event [RAD-X6] request upon initial subscription complete to get the latest context and content. This is newly introduced with the DiagnosticReport events.

. For content sharing, FHIRcast requires the hub to keep track of the latest context and content and defined a version for each. This is necessary so that the Get Current Context request can get the latest information (e.g. in case the subscriber has an race condition with version conflict).
    * However, this requires the Hub to be aware of how to apply all events in a consistent way with respect to all subscribers.
    * But FHIRcast also allows subscribers to use its own policy to decide if and how to apply the events.
    * Therefore I think requiring the Hub to maintain one true view of the latest context and content is an over burden to the Hub. For many messaging application design, it is better to use event sourcing pattern. Basically the Hub maintains an in order list of events, but it is agnostic about the content. Subscribers maintain their version and can retrieve all events from a given starting point. Then it will apply all the events according to its policy.
    ** This can be a batch request, returning a collection of events; or it can trigger a sequence of events.

. The FHIR resources used in the event can be transient. e.g. the DiagnosticReport resource used as a reporting context does not have to be the DiagnosticReport eventuallly being persisted (e.g. output may not be a FHIR resource, or the Report Creator should control the ID generated, not by the Application Invoker)

. Do we need to send *-open events for all referenced resources? Or are they implicit?

. How to explicitly communicate report complete?
    * What is the FHIRcast semantics of *-close?

. Since applications do not communicate with each other directly and know the context of each applications, how can an application get what the current state? Especially late joining application?

. How do you move a collaborating group of apps to a new patient / study context?

. Is it correct that the FHIR resources used in FHIRcast does not have to be a resource fully conformed to even the baseline FHIR resource specification?
    * e.g. In many examples, DiagnosticReport resource does not contain attribute #code# which is 1:1 in the resource profile.

. For the resources to be used in an event, are we required to define the resource profile using fsh and sushi and then in the event definition, referenced the defined resource profile?
    * The full event will not be validated by IG, but at least a valid example resource can be created and validated by IG, which can then be used as the resource context.
    * So instead of a textual Description in the event template, the Description can reference the resource profile instead.

. Is the event naming convention [FHIR resource]-[suffix] too restrictive? Or is [suffix] can be any string(s), not just the [open | close | update | select]?
    * e.g. The same FHIR resource may be used in different context with different semantics.

. 2.3.3 Context: If a Hub is only required to at least send the elemented indicated in the FHIR Operation to generate context, does it mean then all the other elements in the received event may not be available to the subscribers?
    * If so, then the subscribers cannot rely on any of those elements to exist in the event
    * This may be confusing reading the examples since the examples always have the full content while the FHIR operation to generate context is often quite simple with one or two elements only.

. Is WSS desirable? Any concern by implementers using websocket? Should webhook be required as well?

. When requesting a change context with a compound context like DiagnosticReport-open which includes DiagnosticReport, Patient and ImagingStudy, are they treated as one compound context?
    * Where is it defined?
        ** In 2.3.2 Event Name, it stated "The FHIRresource indicates the focus of the event; the suffix defines the type of event.". So it seems to suggest that the resource in the event name indicates which context within the array is the 'focus'. However, there is no definition of what 'focus' means.
            *** Later in the DiagnosticReport-close event, it seems to indicate that only the context in 'focus' is required.
    * When the DiagnosticReport-close event is sent, should the close event includes the full set of compound context and the hub should verify it?
        ** Or just the DiagnosticReport ID is good enough without the rest (patient and study)?
    * If the context is indeed multiple independent ones rather than a single compound context, does it mean that some subscribers may send patient-close to just close the patient context without the full context? Don't think this is what intented.
        ** In 2.3.3 Context, it stated "In the case the resource refers to other FHIR resources that represent their own context, these can be included as well.". However, it is not clear what "represent their own context" means. Are these additional context being 'sub-context' of the context in focus, or are they independent context.
    * Or better, should DiagnosticReport resource be the root and then patienet and study being just elements within the DR resource. So it is clear as one context.

. Should the events be thin event or rich event?
    * If just provide the FHIR resource ID but not more content, then
        ** Does the actual FHIR resource exist?
        ** Does the subscriber have the right permission to get the content of the resource?
        ** Reliability and dependency of the network?

. Any concern with PHI in the event?

. In 2.3.3 Context, it stated "The key used for indicating a context change event’s FHIR resource SHALL be the lower-case resourceType of the resource". This is not true for DiagnosticReport-* since the corresponding key is 'report', not 'diagnosticreport'.

. What is the proper mechanism to synchronize app close?
    * Letting the websocket channel to timeout is not a graceful disconnect.

. Request Context Change is HTTP POST, not via websocket
    * This is important because this allows control of who can submit what events, especially with SMART on FHIR and OAuth2 scopes
        ** Other launched methods will need to take this into account

. If an application is already running, how can an application invoker invite the running app to join another session?

. In 2.5.6 Hub generates *-open events, is this necessary given that there is a Get Current Context API for a late subscriber to catch up?
    * It is better for the Hub to have less business logic and participate in any particular workflow.

== Note

. Consider changing the transaction to be more reporting specific

. Where should the report persistence be specified?
    * The report should be persisted somehow

. For the Initiate Reporting Session transaction
    * The resources in context does NOT have to exist as a FHIR resource. They can be transient.
    * But the following has to be actually exist
        ** Patient ID
        ** Study UID
        ** Accession Number
    * Note: The FHIR resource that captures the patient and study may not exist. Hence the resource ID in the event may be transient.
        ** If thet patient and study is known to exist as a FHIR resource, then the FHIR resource should actually reference the actual resource
    * The DiagnosticReport resource context as stored in the hub can be transient

. Add *-open / *-close to the transaction to clarify it is an open or close event.

. Add Special App output DICOM objects and notify the PACS
    * Add subscription to PACS

. Consider DocumentReference, Binary in addition to Observation for carrying different payload.

. Is there a need to know if an app has unsubscribe?
    * Is there a need for the Hub to tear down the session if there is no subscribers

. use the home-open to clear the current context

. For context, if using an internal reference, it means the resource is a transient resource that does not actually exist in any FHIR server.
    * if the resource is a true FHIR resource that exist in some FHIR server, then it should be using an absolute URL.

. Do we need any traffic cop for selection?

== Concept Section

. Information model about session (topic) 1:n context 1:n resources
    * Only one active context at any time
    * Prior studies??

. One session with one type of context?

. For reporting use cases, details like Fleusha calculation, measurements, etc.

. Section distinguish between context and content

. Lifecycle of applications

. FHIRcast information model
    * http://build.fhir.org/ig/HL7/fhircast-docs/5_glossary.html
    * topic / session
    * context
    * content

. Provide guidance on how to use syncerror
    * what considers an error that every other subscribers should be aware of? vs what should be simply ignore but not send syncerror
    * receiving a syncerror does not mean that the app has to do something

. Guidance of when is a good time to send an DiagnosticReport-update event
    * Every mouse movement should not generate an update event
    * also does not have to wait for a DICOM object to be persisted before sending an update event
    * This profile is designed to provide a mechanism for communicating in-progress data

    
