@startuml

hide footbox

participant "Subscriber" as Sub
participant "Read-Only\nSubscriber" as ROSub
participant "Hub" as Hub

Sub->Hub: Subscribe to Reporting Session Request
activate Hub
Hub-->Sub: Subscribe to Reporting Session Response
deactivate Hub

ROSub->Hub: Subscribe to Reporting Session Request
activate Hub
Hub-->ROSub: Subscribe to Reporting Session Response
deactivate Hub

@enduml