@startuml

hide footbox

participant "Subscriber" as Subscriber
participant "Manager" as Manager

Subscriber->Manager: Send SyncError Request
activate Manager
Manager-->Subscriber: Send SyncError Response
deactivate Manager

@enduml