@startuml

hide footbox

participant "Sender" as Sender
participant "Manager" as Manager

Sender->Manager: Unsubscribe Session Request
activate Manager
Manager-->Sender: Unsubscribe Session Response
deactivate Manager

@enduml