@startuml

hide footbox

participant "Subscriber" as Subscriber
participant "Manager" as Manager

Subscriber->Manager: Unsubscribe Session Request
activate Manager
Manager-->Subscriber: Unsubscribe Session Response
deactivate Manager

@enduml