@startuml

hide footbox

participant "Subscriber" as Subscriber
participant "Manager" as Manager

Subscriber->Manager: Connect to Websocket Request
activate Manager
Manager-->Subscriber: Connect to Websocket Response
deactivate Manager

@enduml