@startuml

hide footbox

participant "Sender" as Sender
participant "Receiver" as Receiver

Sender->Receiver: Subscribe to Reporting Session Request
activate Receiver
Receiver-->Sender: Subscribe to Reporting Session Response
deactivate Receiver

@enduml