@startuml

hide footbox

participant "Sender" as Sender
participant "Manager" as Manager

Sender->Manager: Connect to Websocket Request
activate Manager
Manager-->Sender: Connect to Websocket Response
deactivate Manager

@enduml