@startuml

hide footbox

participant "Sender" as Sender
participant "Manager" as Manager

Sender->Manager: Update Report Status Request
activate Manager
Manager-->Sender: Update Report Status Response
deactivate Manager

@enduml