@startuml

hide footbox

participant "Subscriber" as Subscriber
participant "Manager" as Manager

Subscriber->Manager: Subscription Request
activate Manager
Manager-->Subscriber: Subscription Response
deactivate Manager

@enduml