@startuml

hide footbox

participant "Sender" as Sender
participant "Manager" as Manager

== Update Report Content ==

Sender->Manager: Update Report Content Request
activate Manager
Manager-->Sender: Update Report Content Response
deactivate Manager

@enduml