@startuml

hide footbox

participant "Subscriber" as Subscriber
participant "Manager" as Manager

Subscriber->Manager: Get Current Context Request
activate Manager
Manager-->Subscriber: Get Current Context Response
deactivate Manager

@enduml