@startuml

hide footbox

participant "Manager" as Manager
participant "Receiver" as Receiver

Manager->Receiver: Send Event Request
activate Receiver
Receiver-->Manager: Send Event Response
deactivate Receiver

@enduml