@startuml

hide footbox

participant "Manager" as Manager
participant "Subscriber" as Subscriber

Manager->Subscriber: Notification
activate Subscriber
Subscriber-->Manager: Notification Response
deactivate Subscriber

opt In case of asynchronous processing
Subscriber->Manager: Notify Error
activate Manager
Manager-->Subscriber: Notify Error Response
deactivate Manager
end

@enduml