@startuml

hide footbox

participant "Manager" as Manager
participant "Subscriber" as Subscriber

Manager->Subscriber: Error Notification
activate Subscriber
Subscriber-->Manager: Error Notification Response
deactivate Subscriber

@enduml