@startuml

hide footbox

participant "Sender" as Sender
participant "Receiver" as Receiver

Sender->Receiver: Connect to Websocket Request
activate Receiver
Receiver-->Sender: Connect to Websocket Response
deactivate Receiver

@enduml