@startuml

hide footbox

participant "Sender" as Sender
participant "Manager" as Manager

Sender->Manager: Select Report Content Request
activate Manager
Manager-->Sender: Select Report Content Response
deactivate Manager

@enduml