@startuml

hide footbox

participant "Sender" as Sender
participant "Manager" as Manager
participant "Receiver" as Receiver

== Initial Report Context ==

Sender->Manager: Open Report Context Request
activate Manager
Manager-->Sender: Open Report Context Response
deactivate Manager

== Process DiagnosticReport-open Event ==
Manager->Receiver: //Send Context Event [RAD-X9]//
Receiver->Receiver: Initiate Report Context

@enduml