@startuml

hide footbox

participant "Manager" as Manager
participant "Subscriber" as Subscriber

Manager->Subscriber: Notification
activate Subscriber
Subscriber-->Manager: Notification Response
deactivate Subscriber

@enduml