@startuml

hide footbox

actor Radiologist as User
participant "Image Display" as PACS
participant "Report Creator" as Report

User -> PACS: //Open reporting session// [[volume-1.html#15342121-step-1-open-reporting-session Step 1]]
PACS -> Report: //Launch application//
loop
User -> PACS: //Select Patient and Study//
PACS -> PACS: //Open Study and show Chest X-Ray// [[volume-1.html#15342122-step-2-open-study-in-context Step 2]]
User -> PACS: //Measure area of Pneumothorax// [[volume-1.html#15342123-step-3-add-content-optional Step 3]]
User -> Report: //Dictate Report//
User -> PACS: //Select measurements as seen in images// [[volume-1.html#15342124-step-4-select-content-optional Step 4]]
User -> Report: //Auto-populate report with selected measurements//
User -> Report: //Sign-off Report// [[volume-1.html#15342125-step-5-sign-off-report Step 5]]
end

User->PACS: //Close reporting session// [[volume-1.html#15342126-step-6-close-reporting-session Step 6]]

@enduml