@startuml reporting_with_selection

title Reporting with Selection Workflow

actor Radiologist
participant "PACS" as PACS
participant "Data Hub" as Hub
participant "Reporting System" as Report

== Step 1 and 2 ==
note over PACS, Report
Same as Use Case 1
end note

== Step 3: Content Sharing ==

loop
PACS->Hub: Update Context Content [RAD-X5]
Hub->Hub: //Maintain order of content update//
Hub->Report: Send Context Event [RAD-X3]
Report->Report: //Apply event//

Radiologist->PACS: //Select images and/or measurements//\n//as current focus//
PACS->Hub: Select Context Content [RAD-X8]
Hub->Report: Send Context Event [RAD-X3]

Radiologist->Report: //Insert Hyperlink//\n//as a voice command//
note over Radiologist
May be done via voice command
or other methods
end note
Report->Report: //Insert hyperlink in report//\n//to current focused content//
end loop

== Step 4: Close Context and Application ==
note over PACS, Report
Same as Use Case 1
end note

@enduml