@startuml

actor Radiologist as User
participant "Image Display\n(as Driving App\nand Content Sharing App)" as PACS
participant "Hub" as Hub
participant "Report Creator\n(as Synchronizing App\nand Driving App)" as Report

== Step 1: Open Reporting Session ==

User->PACS: //Open reporting session//
PACS->PACS: //Ready to start reporting//
note over PACS
Generate unique session ID
end note

PACS->Hub: Subscribe to reporting session [RAD-Sub]\n//(session 12345)//
Hub->Hub: //Create a new session//\n//if session ID does not exist//

PACS->Report: //Launch Application//

Report->Hub: Subscribe to reporting session [RAD-Sub]\n//(session 12345)//
note over Hub
Hub adds Reporting App to the reporting session.
end note

Report->Hub: Get Current Context [RAD-X6]\n(catch up with current context and content)
Hub-->Report: //Return empty context//

@enduml