@startuml

actor Radiologist as User
participant "Image Display" as PACS
participant "Hub" as Hub
participant "Report Creator" as Report

== Step 6: Terminate Reporting Session ==

User->Report: //Close application//

Report->Hub: Unsubscribe Session [RAD-X7]\n(session 12345)
Hub-->Report: //Accept//
Hub->Hub: //Close channel to Reporting System//

@enduml