# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: ihe.rad.ira
canonical: https://profiles.ihe.net/RAD/IRA
version: 1.0.0-ci
releaseLabel: ci-build
#releaseLabel: ballot
#releaseLabel: Trial-Implementation
#date: 2023-03-17
name: IHE_RAD_IRA
title: "Integrated Reporting Applications"
status: active
publisher:
  - name: IHE Radiology Technical Committee
  - url: https://www.ihe.net/ihe_domains/radiology/
  - email: radiology@ihe.net
contact:
  - name: IHE Radiology Technical Committee
    telecom:
      - system: email
        value: radiology@ihe.net
description: The Integrated Reporting Applications (IRA) profile helps applications that are used together during reporting (e.g., image display, report creator, clinical applications, AI tools, etc) to share information using a standard called FHIRcast. Each application can share what it is doing and the data it is creating, referred to as Context and Content, respectively. Other applications are notified so they can then intelligently synchronize their behavior or use the new data.
license:  CC-BY-4.0
#fhirVersion: 4.0.1
fhirVersion: 5.0.0
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2023+


parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true


pages:
# itemize here each narrative page. Include assigned section numbers when appropriate
  index.md:
    title: 1:XX IRA Home
    generation: markdown
  volume-1.md:
    title: 1:XX IRA Volume 1
    generation: markdown
  rad-x1.md:
    title: 2:3.X1 Subscribe to Reporting Session [RAD-X1]
    generation: markdown
  rad-x2.md:
    title: 2:3.X2 Connect to Notification Channel [RAD-X2]
    generation: markdown
  rad-x3.md:
    title: 2:3.X3 Open Report Context [RAD-X3]
    generation: markdown
  rad-x4.md:
    title: 2:3.X4 Close Report Context [RAD-X4]
    generation: markdown
  rad-x5.md:
    title: 2:3.X5 Update Report Content [RAD-X5]
    generation: markdown
  rad-x6.md:
    title: 2:3.X6 Select Report Content [RAD-X6]
    generation: markdown
  rad-x12.md:
    title: 2:3.X12 Update Report Status [RAD-X12]
    generation: markdown
  rad-x7.md:
    title: 2:3.X7 Unsubscribe Session [RAD-X7]
    generation: markdown
  rad-x8.md:
    title: 2:3.X8 Get Current Context [RAD-X8]
    generation: markdown
  rad-x9.md:
    title: 2:3.X9 Distribute Context Event [RAD-X9]
    generation: markdown
  rad-x10.md:
    title: 2:3.X10 Generate SyncError Event [RAD-X10]
    generation: markdown
  rad-x11.md:
    title: 2:3.X11 Notify Error [RAD-X11]
    generation: markdown
  example.md:
    title: Introduction to Examples
    generation: markdown
  open_study_for_reporting.md:
    title: Open Report Context
    generation: markdown
  update_study_with_measurement.md:
    title: Update Report Content
    generation: markdown
  select_study_and_observation.md:
    title: Select Report Content
    generation: markdown
  update_report_status.md:
    title: Update Report Status
    generation: markdown
  close_study_after_signoff.md:
    title: Close Report Context
    generation: markdown
  testplan.md:
    title: "Test Plan"
    generation: markdown
  issues.md:
    title: Significant Changes and Issues
    generation: markdown
  other.md:
    title: Changes to Other Documents
    generation: markdown
  download.md:
    title: "Download and analysis"
    generation: markdown

menu:
  IRA Home: index.html
  Volume 1:
    Introduction: volume-1.html
    Actors and Transactions: volume-1.html#1xx1-realtime-bidirectional-communication-for-interactive-multimedia-reporting
    Actor Options: volume-1.html#1xx2-ira-actor-options
    Required Groupings: volume-1.html#1xx3-ira-required-actor-groupings
    Overview: volume-1.html#1xx4-ira-overview
    Security Considerations: volume-1.html#1xx5-ira-security-considerations
    Cross-Profile Considerations: volume-1.html#1xx6-ira-cross-profile-considerations
  Volume 2:
    Subscribe to Reporting Session [RAD-X1]: rad-x1.html
    Connect to Notification Channel [RAD-X2]: rad-x2.html
    Open Report Context [RAD-X3]: rad-x3.html
    Close Report Context [RAD-X4]: rad-x4.html
    Update Report Content [RAD-X5]: rad-x5.html
    Select Report Content [RAD-X6]: rad-x6.html
    Update Report Status [RAD-X12]: rad-x12.html
    Unsubscribe Session [RAD-X7]: rad-x7.html
    Get Current Context [RAD-X8]: rad-x8.html
    Distribute Context Event [RAD-X9]: rad-x9.html
    Generate SyncError Event [RAD-X10]: rad-x10.html
    Notify Error [RAD-X11]: rad-x11.html
  Examples:
    Introduction: example.html
    Open Report Context: open_study_for_reporting.html
    Update Report Content: update_study_with_measurement.html
    Select Report Content: select_study_and_observation.html
    Update Report Status: update_report_status.html
    Close Report Context: close_study_after_signoff.html
  Artifacts: artifacts.html
  Other:
    Test Plan: testplan.html
    Changes to Other IHE Specifications: other.html
    Download and Analysis: download.html
