# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: ihe.rad.rtc-imr
canonical: https://profiles.ihe.net/RAD/RTC-IMR
version: 0.1.1
releaseLabel: ci-build
#releaseLabel: ballot
#releaseLabel: Trial-Implementation
#date: 2022-07-25
name: IHE_RAD_RTC_IMR
title: "Realtime Communication for Interactive Multimedia Report (RTC-IMR)"
status: active
publisher:
  - name: IHE Radiology Technical Committee
  - url: https://www.ihe.net/ihe_domains/radiology/
  - email: radiology@ihe.net
contact:
  - name: IHE Radiology Technical Committee
    telecom:
      - system: email
        value: radiology@ihe.net
description: Realtime communication between systems to enable interactive multimedia reporting
license:  CC-BY-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2021+

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true


pages:
# itemize here each narrative page. Include assigned section numbers when appropriate
  index.md:
    title: 1:XX. RTC-IMR Home
    generation: markdown
  volume-1.md:
    title: 1:XX. RTC-IMR Volume 1
    generation: markdown
  rad-x1.md:
    title: 2:3.X1 Subscribe to Reporting Session [RAD-X1]
    generation: markdown
  rad-x2.md:
    title: 2:3.X2 Connect to Notification Channel [RAD-X2]
    generation: markdown
  rad-x3.md:
    title: 2:3.X3 Initiate Report Context [RAD-X3]
    generation: markdown
  rad-x4.md:
    title: 2:3.X4 Terminate Report Context [RAD-X4]
    generation: markdown
  rad-x5.md:
    title: 2:3.X5 Update Report Content [RAD-X5]
    generation: markdown
  rad-x6.md:
    title: 2:3.X6 Select Report Content [RAD-X6]
    generation: markdown
  rad-x7.md:
    title: 2:3.X7 Unsubscribe Session [RAD-X7]
    generation: markdown
  rad-x8.md:
    title: 2:3.X8 Get Current Context [RAD-X8]
    generation: markdown
  rad-x9.md:
    title: 2:3.X9 Distribute Context Event [RAD-X9]
    generation: markdown
  rad-x10.md:
    title: 2:3.X10 Generate SyncError Event [RAD-X10]
    generation: markdown
  rad-x11.md:
    title: 2:3.X11 Notify Error [RAD-X11]
    generation: markdown
  example.md:
    title: Introduction to Examples
    generation: markdown
  open_study_for_reporting.md:
    title: Initiate Report Context
    generation: markdown
  update_study_with_measurement.md:
    title: Update Report Content
    generation: markdown
  select_study_and_observation.md:
    title: Select Report Content
    generation: markdown
  update_report_status.md:
    title: Update Report Status
    generation: markdown
  close_study_after_signoff.md:
    title: Terminate Report Context
    generation: markdown
  testplan.md:
    title: "Test Plan"
    generation: markdown
  issues.md:
    title: Open and Closed issues
    generation: markdown
  other.md:
    title: Changes to Other Profiles
    generation: markdown
    
menu:
  RTC-IMR Home: index.html
  Volume 1:
    Introduction: volume-1.html
    Actors and Transactions: volume-1.html#1xx1-realtime-bidirectional-communication-for-interactive-multimedia-reporting
    Actor Options: volume-1.html#1xx2-rtc-imr-actor-options
    Required Groupings: volume-1.html#1xx3-rtc-imr-required-actor-groupings
    Overview: volume-1.html#1xx4-rtc-imr-overview
    Security Considerations: volume-1.html#1xx5-rtc-imr-security-considerations
    Cross-Profile Considerations: volume-1.html#1xx6-rtc-imr-cross-profile-considerations
  Volume 2:
    Subscribe to Reporting Session [RAD-X1]: rad-x1.html
    Connect to Notification Channel [RAD-X2]: rad-x2.html
    Initiate Report Context [RAD-X3]: rad-x3.html
    Terminate Report Context [RAD-X4]: rad-x4.html
    Update Report Content [RAD-X5]: rad-x5.html
    Select Report Content [RAD-X6]: rad-x6.html
    Unsubscribe Session [RAD-X7]: rad-x7.html
    Get Current Context [RAD-X8]: rad-x8.html
    Distribute Context Event [RAD-X9]: rad-x9.html
    Generate SyncError Event [RAD-X10]: rad-x10.html
    Notify Error [RAD-X11]: rad-x11.html
  Examples:
    Introduction: example.html
    Initiate Report Context: open_study_for_reporting.html
    Update Report Content: update_study_with_measurement.html
    Select Report Content: select_study_and_observation.html
    Update Report Status: update_report_status.html
    Terminate Report Context: close_study_after_signoff.html
  Test Plan: testplan.html
  Artifacts: artifacts.html
  Other: other.html
